# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0
# Following source doesn't work in most setups
ignored:
  - SC1090
  - SC1091
