name: goreleaser

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: 1.16.2
          ## publishing is only for tags
          args: release --clean ${{ (startsWith(github.ref, 'refs/tags/') && '') || '--snapshot --skip-publish' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
