name: Trunk Check

## In Git repository
## run trunk.io linter

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  trunk:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        id: trunk
        uses: trunk-io/trunk-action@v1
        with:
          arguments: --github-annotate-new-only=false
          check-mode: ${{ (github.event.action == 'workflow_dispatch' && 'all') || '' }}
